### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by navanchauhan** [marmos91/moviebot#1]
Output of results.csv:

```
Website,Link
```

**Comment by marmos91** [comment]
Hi @navanchauhan, this repository is only meant for education purposes and the code would only work for some specific cases. In fact it was written during a lecture on web crawling. I will update the readme to reflect the repository nature in order to avoid future misunderstandings. Thank you for pointing it out. :)

**Comment by navanchauhan** [comment]
Nah, I made it work on my own. I thought this was an upcoming project
